"""empty message

Revision ID: 10324a593899
Revises: 18dc40ad58ac
Create Date: 2019-11-28 03:29:23.584091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10324a593899'
down_revision = '18dc40ad58ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
